# Generated by Django 4.2.23 on 2025-06-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
