# Generated by Django 4.2.23 on 2025-06-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0002_jobposting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='published_at',
            field=models.DateField(null=True),
        ),
    ]
