# Generated by Django 4.2.23 on 2025-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0003_alter_jobposting_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_link',
            field=models.URLField(null=True),
        ),
    ]
