# Generated by Django 4.2.23 on 2025-06-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0004_company_api_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datascraper.vendor'),
        ),
    ]
