# Generated by Django 4.2.23 on 2025-06-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0005_company_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
