# Generated by Django 4.2.23 on 2025-06-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0006_jobposting_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=2)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
