# Generated by Django 4.2.23 on 2025-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0007_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crawled_at',
            field=models.DateField(null=True),
        ),
    ]
