# Generated by Django 4.2.23 on 2025-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0008_company_crawled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='vendor_job_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
