# Generated by Django 4.2.23 on 2025-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0009_alter_jobposting_vendor_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_usa',
            field=models.BooleanField(default=False),
        ),
    ]
