# Generated by Django 4.2.23 on 2025-07-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0010_jobposting_is_usa'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_hybrid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
