# Generated by Django 4.2.23 on 2025-07-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0012_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datascraper.state'),
        ),
    ]
