# Generated by Django 4.2.23 on 2025-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0013_jobposting_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
