# Generated by Django 4.2.23 on 2025-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0014_remove_jobposting_programming_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(default='', max_length=255),
        ),
    ]
